name: Scrape
on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  '0 12 * * *'
jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ['blekinge', 'jonkoping', 'kalmar', 'kronoberg', 'orebro']
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Scrape the data
        run: python3 run.py ${{ matrix.region }}
      - name: Set autostash
        run: |
          git config rebase.autoStash true
      - name: Commit the data
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Pierre Mesure (Github Actions)
          author_email: pierre@mesu.re
          message: 'Updating the data for Region ${{ matrix.region }}'
          add: '*.csv'
