name: Scrape
on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  '0 12 * * *'
jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ['blekinge', 'jonkoping', 'kalmar', 'kronoberg', 'orebro']
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Scrape the data
        run: python3 run.py ${{ matrix.region }}
      - run: ls
      - name: Commit the data
        run: |
          git pull
          git config --global user.name 'Pierre Mesure'
          git config --global user.email 'pierre@mesu.re'
          git config --global core.autocrlf false
          git add --renormalize *.csv
          git commit -am "Updating the data for Region ${{ matrix.region }}"
          git push
