name: Scrape Times
on:
  workflow_dispatch:
  schedule:
    - cron:  '0/30 * * * *'
jobs:
  scrape:
    name: Scrape times
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        region: ['10', '20', '09', '21', '13', '23', '06', '08', '07', '25', '12', '01', '04', '03', '17', '24', '22', '19', '14', '18', '05']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip3 install -r requirements.txt
      - name: Scrape the data
        run: python3 scrape_times.py ${{ matrix.region }}
      - name: Set autostash
        run: git config rebase.autoStash true
      - name: Commit the data
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Pierre Mesure (Github Actions)
          author_email: pierre@mesu.re
          message: 'Updating the times for Region ${{ matrix.region }}'
          add: '*.json'
          pull_strategy: '--rebase'
